{
 "title": "Environment Monitors",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "watchdog",
    "label": "Watchdog Device",
    "query": "label_values(watchdog_tempF, service)"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "fahrenheit" }
   ],
   "targets": [
    {
     "expr": "watchdog_tempF{job=~\"$watchdog\"}",
     "legendFormat": "{{ deviceName }}"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "watchdog_humidity{job=~\"$watchdog\"}",
     "legendFormat": "{{ deviceName }}"
    }
   ]
  },
  {
   "title": "Airflow",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "flowcfm" }
   ],
   "targets": [
    {
     "expr": "watchdog_airflow{job=~\"$watchdog\"}",
     "legendFormat": "{{ deviceName }}"
    }
   ]
  },
  {
   "title": "Sound",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    {
     "expr": "watchdog_sound{job=~\"$watchdog\"}",
     "legendFormat": "{{ deviceName }}"
    }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "expr": "watchdog_light{job=~\"$watchdog\"}",
     "legendFormat": "{{ deviceName }}"
    }
   ]
  }
 ]
}